# Generated by Django 3.0 on 2021-08-26 20:18

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=50, unique=True, verbose_name='类别')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotRate', models.IntegerField(default=0, verbose_name='热度')),
            ],
            options={
                'ordering': ('hotRate',),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='创作时间')),
                ('title', models.CharField(max_length=50, verbose_name='博客标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='博客内容')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Hot', verbose_name='热度')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.BlogType', verbose_name='博客分类')),
            ],
            options={
                'ordering': ('-hot',),
            },
        ),
    ]
