# Generated by Django 3.0 on 2021-09-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writeTime', models.DateTimeField(auto_created=True)),
                ('userName', models.CharField(max_length=80, verbose_name='用户')),
                ('content', models.TextField(max_length=500, verbose_name='评论内容')),
                ('blogF', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Blog', verbose_name='具体对应的博客')),
            ],
        ),
    ]
