# Generated by Django 3.0 on 2021-08-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=50, verbose_name='类别')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('url', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='文件路径')),
                ('imgSize', models.CharField(default='1980*1080', max_length=30, verbose_name='图片尺寸')),
                ('hot', models.IntegerField(default=0, verbose_name='图片观看热度')),
                ('download', models.IntegerField(default=0, verbose_name='被下载次数')),
                ('imgType', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallpaper.ImgType')),
            ],
        ),
    ]
